-- db/schema.sql
-- DROP DATABASE IF EXISTS summaries;

DROP DATABASE IF EXISTS news;

CREATE DATABASE news;

\c news

DROP TABLE IF EXISTS articles;

CREATE TABLE articles (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    abstract VARCHAR(255) NOT NULL,
    summary_type INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);